-- CreateTable
CREATE TABLE "page" (
    "id"      int           PRIMARY KEY GENERATED BY DEFAULT as IDENTITY,
    "name"    VARCHAR(250)  NOT NULL,
    "title"   VARCHAR(250)  NOT NULL,
    "content" TEXT          NOT NULL
);
